services:
  metastore:
    image: postgres:11
    hostname: metastore
    environment:
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.1

  master:
    image: hadoop-hive-spark-master:latest
    hostname: master
    depends_on:
      - metastore
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master
    ports:
      - "4040:4040"
      - "8020:8020"
      - "8086:8080"
      - "8088:8088"
      - "9870:9870"
      - "10000:10000"
    volumes:
      - namenode:/opt/hadoop/dfs/name
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.9

  worker1:
    image: hadoop-hive-spark-worker:latest
    hostname: worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.3

  worker2:
    image: hadoop-hive-spark-worker:latest
    hostname: worker2
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.4
      SPARK_LOCAL_HOSTNAME: worker2
    ports:
      - "8043:8042"  
      - "8082:8081"  
      - "9865:9864"  
    volumes:
      - datanode2:/opt/hadoop/dfs/data
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.4

  history:
    image: hadoop-hive-spark-history:latest
    hostname: history
    container_name: spark-history
    depends_on:
      - master
      - worker1
      - worker2
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.5
      SPARK_LOCAL_HOSTNAME: history
    ports:
      - "18080:18080"
      - "19888:19888"
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.5

  jupyter:
    image: hadoop-hive-spark-jupyter:latest
    hostname: jupyter
    container_name: jupyter
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.6
      SPARK_LOCAL_HOSTNAME: jupyter
    depends_on:
      - master
      - worker1
      - worker2
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebook:/home/jupyter
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.6

  nifi: 
    cap_add:
      - NET_ADMIN 
    image: apache/nifi
    container_name: nifi
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=dataPipeAppPwd!
    ports:
      - "8089:8080/tcp"
      - "8443:8443/tcp" 
      - "514:514/tcp"
      - "514:514/udp"
      - "2055:2055/udp"
    restart: unless-stopped
    networks:
      sparknet:
        ipv4_address: 172.28.1.7

  zeppelin:
    image: apache/zeppelin:0.11.2
    container_name: zeppelin-notebook
    ports:
      - "8084:8080"
    volumes:
      - ./spark:/zeppelin/spark
      - ./notebooks:/zeppelin/notebook
    environment:
      - "MASTER=172.28.1.6"
      - "SPARK_MASTER=172.28.1.6"
      - "SPARK_HOME=/zeppelin/spark"
    networks:
      sparknet:
        ipv4_address: 172.28.1.12

  griffin:
    image:  apachegriffin/griffin_spark2:0.3.0
    hostname: griffin
    links:
      - es
    environment:
      ES_HOSTNAME: es
    volumes:
      - /var/lib/mysql
    ports:
      - 32122:2122
      - 38088:8088  # yarn rm web ui
      - 33306:3306  # mysql
      - 35432:5432  # postgres
      - 38042:8042  # yarn nm web ui
      - 39083:9083  # hive-metastore
      - 38998:8998  # livy
      - 38080:8080  # griffin ui
    tty: true
    container_name: griffin
    networks:
      sparknet:
        ipv4_address: 172.28.1.11

  es:
    image: apachegriffin/elasticsearch
    hostname: es
    ports:
      - 39200:9200
      - 39300:9300
    container_name: es
    networks:
      sparknet:
        ipv4_address: 172.28.1.10

volumes:
  nifi-conf:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

