site_name: Data Testing Automation building blocks
site_url: https://testautomationmultiverse.github.io/Data_Quality_Engineering/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search

nav:
  - Home:
    - index.md
    - data_governance.md
  - Data Testing Concepts:
    - BasicConcepts/intro.md
    - BasicConcepts/ETLTesting.md
    - BasicConcepts/Database_Monitoring.md
    - BasicConcepts/data_monitoring.md
  - Test Artifacts:
    - test artifacts/Test_Strategy.md
    - test artifacts/Test_Plan.md
    - test artifacts/TraceabilityMatrix.md
    - test artifacts/Documentation.md
    - test artifacts/Defect_Report.md
  - data_engineering_tool_ecosystem.md
  - learning-plan-and-resources.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2024
